// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetHotel.Health.Infrastructure.Persistence;

#nullable disable

namespace PetHotel.Health.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HealthDbContext))]
    [Migration("20260611005141_AddParasitesAndVetContact")]
    partial class AddParasitesAndVetContact
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("health")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetHotel.Health.Domain.HealthRecords.HealthRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("Pet")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Pet")
                        .IsUnique();

                    b.ToTable("health_records", "health");
                });

            modelBuilder.Entity("PetHotel.Health.Domain.HealthRecords.ParasiteTreatment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppliedOn")
                        .HasColumnType("date");

                    b.Property<Guid?>("HealthRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("NextDueOn")
                        .HasColumnType("date");

                    b.Property<string>("ProductName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.ToTable("parasite_treatments", "health");
                });

            modelBuilder.Entity("PetHotel.Health.Domain.HealthRecords.Vaccination", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppliedOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<Guid?>("HealthRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.ToTable("vaccinations", "health");
                });

            modelBuilder.Entity("PetHotel.Health.Domain.HealthRecords.HealthRecord", b =>
                {
                    b.OwnsOne("PetHotel.Health.Domain.HealthRecords.VetContact", "VetContact", b1 =>
                        {
                            b1.Property<Guid>("HealthRecordId");

                            b1.Property<string>("Clinic");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Phone")
                                .IsRequired();

                            b1.HasKey("HealthRecordId");

                            b1.ToTable("health_records", "health");

                            b1
                                .ToJson("VetContact")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HealthRecordId");
                        });

                    b.Navigation("VetContact");
                });

            modelBuilder.Entity("PetHotel.Health.Domain.HealthRecords.ParasiteTreatment", b =>
                {
                    b.HasOne("PetHotel.Health.Domain.HealthRecords.HealthRecord", null)
                        .WithMany("ParasiteTreatments")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PetHotel.Health.Domain.HealthRecords.Vaccination", b =>
                {
                    b.HasOne("PetHotel.Health.Domain.HealthRecords.HealthRecord", null)
                        .WithMany("Vaccinations")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PetHotel.Health.Domain.HealthRecords.HealthRecord", b =>
                {
                    b.Navigation("ParasiteTreatments");

                    b.Navigation("Vaccinations");
                });
#pragma warning restore 612, 618
        }
    }
}
