// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetHotel.Registry.Infrastructure.Persistence;

#nullable disable

namespace PetHotel.Registry.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RegistryDbContext))]
    partial class RegistryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("registry")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetHotel.Registry.Domain.Packs.Pack", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("packs", "registry");
                });

            modelBuilder.Entity("PetHotel.Registry.Domain.Pets.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BehaviorNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Breed")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Destructiveness")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Fear")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MicrochipCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool?>("Neutered")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhotoKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Reactivity")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Sex")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Sociability")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TutorId");

                    b.ToTable("pets", "registry");
                });

            modelBuilder.Entity("PetHotel.Registry.Domain.Tutors.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("tutors", "registry");
                });

            modelBuilder.Entity("PetHotel.Registry.Domain.Packs.Pack", b =>
                {
                    b.OwnsMany("PetHotel.Registry.Domain.Packs.PackMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("PackId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("PetId");

                            b1.HasKey("PackId", "__synthesizedOrdinal");

                            b1.ToTable("packs", "registry");

                            b1
                                .ToJson("Members")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PackId");
                        });

                    b.Navigation("Members");
                });

            modelBuilder.Entity("PetHotel.Registry.Domain.Pets.Pet", b =>
                {
                    b.OwnsMany("PetHotel.Registry.Domain.Pets.Belonging", "Belongings", b1 =>
                        {
                            b1.Property<Guid>("PetId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Notes");

                            b1.Property<int>("Quantity");

                            b1.HasKey("PetId", "__synthesizedOrdinal");

                            b1.ToTable("pets", "registry");

                            b1
                                .ToJson("Belongings")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.OwnsOne("PetHotel.Registry.Domain.Pets.FeedingRoutine", "FeedingRoutine", b1 =>
                        {
                            b1.Property<Guid>("PetId");

                            b1.Property<string>("FoodName")
                                .IsRequired();

                            b1.Property<int>("FoodSource");

                            b1.PrimitiveCollection<string>("MealTimes")
                                .IsRequired();

                            b1.Property<string>("PortionSize");

                            b1.Property<string>("Restrictions");

                            b1.HasKey("PetId");

                            b1.ToTable("pets", "registry");

                            b1
                                .ToJson("FeedingRoutine")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.Navigation("Belongings");

                    b.Navigation("FeedingRoutine");
                });

            modelBuilder.Entity("PetHotel.Registry.Domain.Tutors.Tutor", b =>
                {
                    b.OwnsMany("PetHotel.Registry.Domain.Tutors.AuthorizedPickup", "AuthorizedPickups", b1 =>
                        {
                            b1.Property<Guid>("TutorId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Document");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("TutorId", "__synthesizedOrdinal");

                            b1.ToTable("tutors", "registry");

                            b1
                                .ToJson("AuthorizedPickups")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TutorId");
                        });

                    b.OwnsOne("PetHotel.Registry.Domain.Tutors.BillingInfo", "Billing", b1 =>
                        {
                            b1.Property<Guid>("TutorId");

                            b1.Property<string>("AddressLine1");

                            b1.Property<string>("AddressLine2");

                            b1.Property<string>("BillingEmail");

                            b1.Property<string>("City");

                            b1.Property<string>("Document")
                                .IsRequired();

                            b1.Property<string>("PostalCode");

                            b1.Property<string>("State");

                            b1.HasKey("TutorId");

                            b1.ToTable("tutors", "registry");

                            b1
                                .ToJson("Billing")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TutorId");
                        });

                    b.OwnsMany("PetHotel.Registry.Domain.Tutors.Consent", "Consents", b1 =>
                        {
                            b1.Property<Guid>("TutorId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTimeOffset>("DecidedAt");

                            b1.Property<bool>("Granted");

                            b1.Property<string>("TermsVersion")
                                .IsRequired();

                            b1.Property<int>("Type");

                            b1.HasKey("TutorId", "__synthesizedOrdinal");

                            b1.ToTable("tutors", "registry");

                            b1
                                .ToJson("Consents")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TutorId");
                        });

                    b.OwnsMany("PetHotel.Registry.Domain.Tutors.EmergencyContact", "EmergencyContacts", b1 =>
                        {
                            b1.Property<Guid>("TutorId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Phone")
                                .IsRequired();

                            b1.Property<string>("Relationship");

                            b1.HasKey("TutorId", "__synthesizedOrdinal");

                            b1.ToTable("tutors", "registry");

                            b1
                                .ToJson("EmergencyContacts")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TutorId");
                        });

                    b.Navigation("AuthorizedPickups");

                    b.Navigation("Billing");

                    b.Navigation("Consents");

                    b.Navigation("EmergencyContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
